### ISSUE TITLE
Fix entry box in load data form

### ISSUE THREAD

**Issue by Joseph-Lyvers** [ilcartographer/embrace-visualization#24]
Currently, the entry box in load data form is not read at all, and attempting to load a file through that alone will cause an error

**Comment by Joseph-Lyvers** [comment]
can we just remove the entry box?

**Comment by Jonathan-Dickinson** [comment]
> can we just remove the entry box?

I think that is a good idea. For the purposes of this project, I don't think it is necessary to have that entry box.
